version: '3'
services:
  mongodb_superwoovi:
    image: mongo:4.4.6
    container_name: mongodb_superwoovi
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=superwoovi
      - MONGO_INITDB_ROOT_USERNAME=superwoovi
      - MONGO_INITDB_ROOT_PASSWORD=superwoovi
    networks:
      - superwoovi_network
  mqtt:
    container_name: mqtt-container
    image: eclipse-mosquitto:1.6
    restart: always
    ports:
      - 1883:1883
    networks:
      - superwoovi_network

networks:
  superwoovi_network:
    driver: bridge
