version: '3'
services:
  influxdb:
    container_name: influxdb-container
    image: influxdb:2.6-alpine
    ports:
      - '8086:8086'
    networks:
      - influx_mqtt_network
    environment:
      - INFLUXDB_DB=superwoovi
      - INFLUXDB_USER=superwoovi
      - INFLUXDB_USER_PASSWORD=superwoovi
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  mqtt:
      container_name: mqtt-container
      image: eclipse-mosquitto:1.6
      restart: always
      ports:
        - 1883:1883
      networks:
        - influx_mqtt_network

networks:
  influx_mqtt_network:
    driver: bridge
