import Head from 'next/head';

/**
 * Home component
 * @returns {JSX.Element}
 */
export default function Home(): JSX.Element {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="text-3xl font-bold color-green">Hello world!</h1>
		</>
	);
}
